{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

# This program and the accompanying materials are
# made available under the terms of the Eclipse Public License v2.0 which accompanies
# this distribution, and is available at https://www.eclipse.org/legal/epl-v20.html
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Copyright Contributors to the Zowe Project.

package:
  name: "{{ data.get('name')|lower }}"
  version: "{{ data.get('version') }}"

source:
  path: ../../plugin

build:
  number: "{{ data.get('buildnumber') }}"
  string: "zowe"
{{ data.get('noarch') }}

#  features:
#    - zowe

about:
  home: "{{ data.get('homepage') }}"
  license: "{{ data.get('license') }}"
  license_file: "LICENSE"
  summary: "{{ data.get('description') }}"
  doc_url: "https://docs.zowe.org"
