{% set data = load_setup_py_data(setup_file='./setup.py', from_recipe_dir=True) %}

# This example is opinionated toward getting metata from an app framework plugin
# That is not required, and you can write your own meta.yaml instead.
# But for consistency if your package is for multiple zowe components
# You should ensure that all metadata for the different components is related
# So that end users can see the relationship.

package:
  name: "{{ data.get('name')|lower }}"
  version: "{{ data.get('version') }}"

source:
  path: ../../plugin

build:
  number: "{{ data.get('buildnumber') }}"
  string: "zowe"
{{ data.get('noarch') }}

#  features:
#    - zowe

about:
  home: "{{ data.get('homepage') }}"
  license: "{{ data.get('license') }}"
#  license_file: "LICENSE"
  summary: "{{ data.get('description') }}"
  doc_url: "https://docs.zowe.org"
